#!/usr/bin/env bash

#Script for executing leelaz with best weights remotely.

set -eu
source ../config.sh
gcloud compute ssh "$INSTANCE_NAME" --zone "$ZONE" --command "/leela/leelaz -g -w /leela/best-network.gz -b 0 -t 16"
